name: 'Add to web3'
description: 'Publish your files and websites to Storacha'
author: olizilla
branding:
  icon: 'box'
  color: 'white'

inputs:
  path_to_add:
    description: 'Directory path to add to IPFS'
    required: true

  secret_key:
    description: 'The base64 encoded key to use to sign UCAN invocations. Create one using `storacha key create`. See: https://github.com/storacha/upload-service/tree/main/packages/cli#storacha_principal'
    required: true

  proof:
    description: 'A base64 encoded UCAN delegating capabilities the secret signing key above. Create using `storacha delegation create --base64`'
    required: true

  hidden:
    description: 'Include paths that start with "."'
    required: false
    default: 'false'

  wrap:
    description: 'If `path_to_add` points to a file it will be wrapped in a directory to preserve the filename. To disable that set wrap: "false"'
    required: false
    default: 'true'

outputs:
  cid:
    description: 'The IPFS Content ID for path_to_add'
    value: ${{ steps.get_cid.outputs.cid }}

  url:
    description: 'The IPFS Gateway URL'
    value: ${{ steps.get_url.outputs.url }}

runs:
  using: "composite"
  steps:
    - run: npm install -g @storacha/cli
      shell: bash

    - run: storacha space add ${{ inputs.proof }}
      env:
        STORACHA_PRINCIPAL: ${{ inputs.secret_key }}
      shell: bash

    - run: storacha up ${{ inputs.path_to_add }} --json --hidden=${{ inputs.hidden }} --wrap=${{ inputs.wrap }} | tee ./storacha_up_output.json
      env:
        STORACHA_PRINCIPAL: ${{ inputs.secret_key }}
      shell: bash
    
    # expect `./storacha_up_output.json` to contain "{ "root": { "/":  "bafy..." }}
    - name: fail if no CID in response
      run: jq --exit-status --raw-output '.root."/"' ./storacha_up_output.json
      shell: bash

    - id: get_cid
      run: echo "cid=$(jq --exit-status --raw-output '.root."/"' ./storacha_up_output.json)" >> "$GITHUB_OUTPUT"
      shell: bash

    - id: get_url
      run: echo "url=https://${{ steps.get_cid.outputs.cid }}.ipfs.storacha.link" >> "$GITHUB_OUTPUT"
      shell: bash
