name: 'Add to web3'
description: 'Publish your files and websites to web3.storage'
author: olizilla
branding:
  icon: 'box'
  color: 'white'

inputs:
  path_to_add:
    description: 'Directory path to add to IPFS'
    required: true

  secret_key:
    description: 'The base64 encoded key to use to sign UCAN invocations. Create one using `w3 key create`. See: https://github.com/web3-storage/w3cli#w3_principal'
    required: true

  proof:
    description: 'A base64 encoded UCAN delegating capabilities the secret signing key above. Create using `w3 delegation create --base64`'
    required: true

  include_hidden:
    description: 'Include paths that start with "."'
    required: false
    default: 'false'

  no_wrap:
    description: 'Advanced: if `path_to_add` points to a file it will be wrapped in a directory to preserve the filename. To disable that set no_wrap: "true"'
    required: false
    default: 'false'

outputs:
  cid:
    description: 'The IPFS Content ID for path_to_add'
    value: ${{ steps.get_cid.outputs.cid }}

  url:
    description: 'The IPFS Gateway URL'
    value: ${{ steps.get_url.outputs.url }}

runs:
  using: "composite"
  steps:
    - run: npm install -g @web3-storage/w3cli
      shell: bash

    - run: w3 space add ${{ inputs.proof }}
      env:
        W3_PRINCIPAL: ${{ inputs.secret_key }}
      shell: bash

    - run: w3 up ${{ inputs.path_to_add }} --json | tee ./w3_up_output.json
      if: ${{ inputs.no_wrap !== 'true' }}
      env:
        W3_PRINCIPAL: ${{ inputs.secret_key }}
      shell: bash

    - run: w3 up ${{ inputs.path_to_add }} --json --no-wrap | tee ./w3_up_output.json
      if: ${{ inputs.no_wrap === 'true' }}
      env:
        W3_PRINCIPAL: ${{ inputs.secret_key }}
      shell: bash
    
    # expect `./w3_up_output.json` to contain "{ "root": { "/":  "bafy..." }}
    - name: fail if no CID in response
      run: jq --exit-status --raw-output '.root."/"' ./w3_up_output.json
      shell: bash

    - id: get_cid
      run: echo "cid=$(jq --exit-status --raw-output '.root."/"' ./w3_up_output.json)" >> "$GITHUB_OUTPUT"
      shell: bash

    - id: get_url
      run: echo "url=https://${{ steps.get_cid.outputs.cid }}.ipfs.w3s.link" >> "$GITHUB_OUTPUT"
      shell: bash
