name: 'Add to web3'
description: 'Publish your files and websites to web3.storage'
author: olizilla
branding:
  icon: 'box'  
  color: 'white'
inputs:
  path_to_add:
    description: 'Directory path to add to IPFS'
    required: true
  web3_token:
    description: 'API token for web3.storage'
    required: true
  web3_api:
    description: 'API URL'
    required: true
    default: 'https://api.web3.storage'
outputs:
  cid:
    description: 'The IPFS Content ID for the directory'
runs:
  using: 'node12'
  main: 'dist/index.js'
