name: 'Add to web3'
description: 'Publish your files and websites to web3.storage'
author: olizilla
branding:
  icon: 'box'  
  color: 'white'
inputs:
  path_to_add:
    description: 'Directory path to add to IPFS'
    required: true
  web3_token:
    description: 'API token for web3.storage'
    required: true
  web3_api:
    description: 'API URL'
    required: true
    default: 'https://api.web3.storage'
  wrap_with_directory:
    description: 'Boolean. Default: `false`. Should the path_to_add be wrapped in a diretory when creating the IPFS DAG. For most folks using this, the default of `false` is fine. If you want to add a single file and preserve the filename in the IPFS DAG you may want to set it to `true`.'
    required: true
    default: 'false'
outputs:
  cid:
    description: 'The IPFS Content ID for the directory'
runs:
  # TODO: we need node14.14 minimum.
  # https://github.com/actions/runner/issues/772
  # using: 'node12'
  # main: 'dist/index.js'
  using: 'docker'
  image: 'Dockerfile'
